In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("netflix_data.csv")
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,4,In a future where the elite inhabit an island ...,International TV
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,93,After a devastating earthquake hits Mexico Cit...,Dramas
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,78,"When an army recruit is found dead, his fellow...",Horror Movies
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,80,"In a postapocalyptic world, rag-doll robots hi...",Action
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,123,A brilliant group of students become card-coun...,Dramas

In [4]:
data["cast"].replace(np.nan, "None",inplace=True)
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,4,In a future where the elite inhabit an island ...,International TV
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,93,After a devastating earthquake hits Mexico Cit...,Dramas
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,78,"When an army recruit is found dead, his fellow...",Horror Movies
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,80,"In a postapocalyptic world, rag-doll robots hi...",Action
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,123,A brilliant group of students become card-coun...,Dramas

In [5]:
def cast_len(val):
    if val == "None":
        return 0
    else:
        return len(str(val).split(", "))
data["Num_of_cast"]=data["cast"].apply(cast_len)
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre,Num_of_cast
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,4,In a future where the elite inhabit an island ...,International TV,11
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,93,After a devastating earthquake hits Mexico Cit...,Dramas,6
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,78,"When an army recruit is found dead, his fellow...",Horror Movies,9
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,80,"In a postapocalyptic world, rag-doll robots hi...",Action,9
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,123,A brilliant group of students become card-coun...,Dramas,12

In [6]:
data.groupby(["type","genre"]).count()

                              show_id  title  director  cast  country  \
type    genre
Movie   Action                    721    721       714   721      706
        Anime Features             19     19        19    19       19
        Children                  502    502       471   502      449
        Classic Movies             77     77        76    77       77
        Comedies                 1074   1074      1056  1074     1048
        Cult Movies                12     12        12    12       12
        Documentaries             751    751       707   751      709
        Dramas                   1384   1384      1373  1384     1353
        Horror Movies             244    244       243   244      240
        Independent Movies         20     20        20    20       20
        International Movies      114    114       110   114      105
        LGBTQ Movies                1      1         1     1        1
        Music                      17     17        17    17       14
        Romantic Movies             3      3         3     3        3
        Sci-Fi                     11     11        11    11       11
        Sports Movies               1      1         0     1        1
        Stand-Up                  321    321       296   321      293
        Thrillers                  49     49        49    49       49
        Uncategorized              56     56        36    56       37
TV Show Anime Series              148    148         9   148      138
        British TV                232    232        23   232      220
        Classic                    21     21         1    21       21
        Crime TV                  369    369        46   369      341
        Docuseries                194    194        21   194      166
        International TV          690    690        46   690      574
        Kids                      359    359        15   359      297
        Reality TV                102    102         1   102       88
        Romantic TV                28     28         1    28       28
        Spanish-Language            2      2         0     2        2
        Stand-Up                   33     33         7    33       31
        TV Action                  37     37         2    37       37
        TV Comedies               110    110         3   110      110
        TV Dramas                  62     62         0    62       62
        TV Horror                  10     10         1    10       10
        TV Sci                      1      1         0     1        1
        TV Shows                   12     12         8    12        7

                              date_added  release_year  duration  description  \
type    genre
Movie   Action                       721           721       721          721
        Anime Features                19            19        19           19
        Children                     502           502       502          502
        Classic Movies                77            77        77           77
        Comedies                    1074          1074      1074         1074
        Cult Movies                   12            12        12           12
        Documentaries                751           751       751          751
        Dramas                      1384          1384      1384         1384
        Horror Movies                244           244       244          244
        Independent Movies            20            20        20           20
        International Movies         114           114       114          114
        LGBTQ Movies                   1             1         1            1
        Music                         17            17        17           17
        Romantic Movies                3             3         3            3
        Sci-Fi                        11            11        11           11
        Sports Movies                  1             1         1            1
        Stand-Up                     321           321       321          321
        Thrillers                     49            49        49           49
        Uncategorized                 56            56        56           56
TV Show Anime Series                 147           148       148          148
        British TV                   231           232       232          232
        Classic                       19            21        21           21
        Crime TV                     369           369       369          369
        Docuseries                   193           194       194          194
        International TV             689           690       690          690
        Kids                         357           359       359          359
        Reality TV                   102           102       102          102
        Romantic TV                   28            28        28           28
        Spanish-Language               2             2         2            2
        Stand-Up                      33            33        33           33
        TV Action                     36            37        37           37
        TV Comedies                  109           110       110          110
        TV Dramas                     62            62        62           62
        TV Horror                     10            10        10           10
        TV Sci                         1             1         1            1
        TV Shows                      12            12        12           12

                              Num_of_cast
type    genre
Movie   Action                        721
        Anime Features                 19
        Children                      502
        Classic Movies                 77
        Comedies                     1074
        Cult Movies                    12
        Documentaries                 751
        Dramas                       1384
        Horror Movies                 244
        Independent Movies             20
        International Movies          114
        LGBTQ Movies                    1
        Music                          17
        Romantic Movies                 3
        Sci-Fi                         11
        Sports Movies                   1
        Stand-Up                      321
        Thrillers                      49
        Uncategorized                  56
TV Show Anime Series                  148
        British TV                    232
        Classic                        21
        Crime TV                      369
        Docuseries                    194
        International TV              690
        Kids                          359
        Reality TV                    102
        Romantic TV                    28
        Spanish-Language                2
        Stand-Up                       33
        TV Action                      37
        TV Comedies                   110
        TV Dramas                      62
        TV Horror                      10
        TV Sci                          1
        TV Shows                       12